/*
  =========================
    ACTIONS 
  =========================
*/

export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_AFRICAN_COUNTRIES = "GET_AFRICAN_COUNTRIES";
export const GET_EUROPEAN_COUNTRIES = "GET_EUROPEAN_COUNTRIES";
export const GET_ASIAN_COUNTRIES = "GET_ASIAN_COUNTRIES";
export const GET_OCEANIC_COUNTRIES = "GET_OCEANIC_COUNTRIES";
export const GET_AMERICAS_COUNTRIES = "GET_AMERICAS_COUNTRIES";
